version: '3.4'

services:
    
    catalogdb:
        image: postgres
    cartdb:
        image: postgres
    
    distributedcache:
     image: redis
    catalog.api:
     image: ${DOCKER_REGISTRY-}catalogapi
     build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    catalog.grpc:
     image: ${DOCKER_REGISTRY-}cataloggrpc
     build:
       context: .
       dockerfile: Services/Catalog/Catalog.gRPC/Dockerfile
    cart.api:
     image: ${DOCKER_REGISTRY-}cartapi
     build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile

    discount.grpc:
     image: ${DOCKER_REGISTRY-}discountgrpc
     build:
       context: .
       dockerfile: Services/Discount/Discount.gRPC/Dockerfile
    orderdb:
     image: mcr.microsoft.com/mssql/server
    messagebroker:
     image: rabbitmq:management
    


    ordering.api:
     image: ${DOCKER_REGISTRY-}orderingapi
     build:
       context: .
       dockerfile: Services/Ordering/Ordering.API/Dockerfile

    yarpapigateway:
     image: ${DOCKER_REGISTRY-}yarpapigateway
     build:
       context: .
       dockerfile: ApiGateways/YarpApiGateway/Dockerfile

    authenticate.api:
     image: ${DOCKER_REGISTRY-}authenticateapi
     build:
       context: .
       dockerfile: Services/Authenticate/Authenticate_Service/Dockerfile

  

volumes:
    postgres_catalog:
    postgres_cart:
    
    






